import { generatePDF } from '../src/index';
import * as fs from 'fs';
import * as path from 'path';

const htmlTemplate = `
<html>
  <body style="
    font-family: Arial, Helvetica, sans-serif;
    color: #1f2937;
    margin: 0;
    padding: 0;
  ">

    <!-- Page Wrapper -->
    <div style="padding: 40px;">

      <!-- Header -->
      <table width="100%" style="margin-bottom: 40px;">
        <tr>
          <td>
            <h1 style="
              margin: 0;
              font-size: 28px;
              color: #111827;
            ">
              INVOICE
            </h1>
            <p style="margin: 4px 0; font-size: 14px;">
              Invoice #: <b>{{invoiceId}}</b>
            </p>
            <p style="margin: 0; font-size: 14px;">
              Date: {{date}}
            </p>
          </td>

          <td align="right">
            <p style="
              margin: 0;
              font-size: 14px;
              color: #6b7280;
            ">
              Your Company Name
            </p>
            <p style="margin: 2px 0; font-size: 13px;">
              company@email.com
            </p>
            <p style="margin: 0; font-size: 13px;">
              +1 (234) 567-890
            </p>
          </td>
        </tr>
      </table>

      <!-- Divider -->
      <div style="
        height: 1px;
        background-color: #e5e7eb;
        margin-bottom: 30px;
      "></div>

      <!-- Billing Info -->
      <table width="100%" style="margin-bottom: 30px;">
        <tr>
          <td>
            <h3 style="
              margin-bottom: 8px;
              font-size: 16px;
              color: #111827;
            ">
              Bill To
            </h3>
            <p style="margin: 0; font-weight: bold;">
              {{customerName}}
            </p>
            <p style="margin: 4px 0; font-size: 14px;">
              {{customerAddress}}
            </p>
          </td>
        </tr>
      </table>

      <!-- Items Table -->
      <table width="100%" cellpadding="8" cellspacing="0" style="
        border-collapse: collapse;
        margin-bottom: 30px;
      ">
        <thead>
          <tr style="background-color: #f3f4f6;">
            <th align="left" style="
              font-size: 14px;
              border-bottom: 1px solid #e5e7eb;
            ">
              Description
            </th>
            <th align="right" style="
              font-size: 14px;
              border-bottom: 1px solid #e5e7eb;
            ">
              Amount
            </th>
          </tr>
        </thead>

        <tbody>
          {{#each items}}
          <tr>
            <td style="
              border-bottom: 1px solid #e5e7eb;
              font-size: 14px;
            ">
              {{this.name}}
            </td>
            <td align="right" style="
              border-bottom: 1px solid #e5e7eb;
              font-size: 14px;
            ">
              \${{this.price}}
            </td>
          </tr>
          {{/each}}
        </tbody>
      </table>

      <!-- Total -->
      <table width="100%" style="margin-bottom: 40px;">
        <tr>
          <td align="right">
            <p style="
              margin: 0;
              font-size: 18px;
              font-weight: bold;
              color: #111827;
            ">
              Total: \${{total}}
            </p>
          </td>
        </tr>
      </table>

      <!-- Footer -->
      <div style="
        text-align: center;
        font-size: 11px;
        color: #6b7280;
        margin-top: 50px;
      ">
        <p style="margin: 0;">
          Thank you for your business
        </p>
        <p style="margin: 4px 0;">
          Generated by <b>pdf-light</b>
        </p>
      </div>

    </div>
  </body>
</html>
`;

async function main() {
  const data = {
    invoiceId: 'INV-2025-001',
    date: '2025-12-25',
    customerName: 'John Doe',
    customerAddress: '1234 Elm St, Springfield, IL',
    items: [
      { name: 'Service A', price: 100 },
      { name: 'Service B', price: 250 },
      { name: 'Tax', price: 35 },
    ],
    total: 385
  };

  try {
    console.log('Generating PDF...');
    const buffer = await generatePDF({
      html: htmlTemplate,
      data: data,
      layout: {
        marginTop: 20,
        marginBottom: 20,
        marginLeft: 20,
        marginRight: 20
      }
    });

    const outputPath = path.join(__dirname, 'invoice.pdf');
    fs.writeFileSync(outputPath, buffer);
    console.log(`PDF generated successfully at: ${outputPath}`);
  } catch (error) {
    console.error('Error generating PDF:', error);
  }
}

main();
